# This is a basic workflow to help you get started with Actions

name: Customer A

env:
  TestVariable1: "TestVar1Value"
  TestVariable2: "TestVar2Value"

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: "Customer A"
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script 1
        run: echo "Hello, world - ${{env.TestVariable1}} ${{env.Username}}"
        shell: pwsh

      # Runs a single command using the runners shell
      - name: Run a one-line script 2
        run: echo "Hello, world - ${{env.TestVariable2}} ${{env.Password}}"
        shell: pwsh
