name: Test

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow the action to get the required token
permissions:
  id-token: write
  contents: read

# Our Azure environment that we want to sign into
env:
  CLIENT_ID: 8e80a94d-b9bc-48ed-8c68-7ebcf3f1e26a
  TENANT_ID: 95877aab-f66b-4cd0-98a0-1218634664fa
  SUBSCRIPTION_ID: cf52a112-fbee-4377-807b-cca5820bc0af

jobs: 
  Test:
      runs-on: windows-latest
      steps:
        # Step that uses our federated workflow identity and creates an Azure CLI session
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{env.CLIENT_ID}}
            tenant-id: ${{env.TENANT_ID}}
            subscription-id: ${{env.SUBSCRIPTION_ID}}
            enable-AzPSSession: true

        # Get resource group using the previously created session
        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
            inlineScript: |
              Get-AzResourceGroup
            azPSVersion: "latest"